### ISSUE TITLE
7zip not found

### ISSUE THREAD

**Issue by juandaqugo** [shubhamchandak94/readcompression#10]
Hello,
I installed HARC succesfully in Centos 7, but when trying to compress it throws this error:
   /harc: line 104: 7z: command not found
I have installed p7zip successfully but It looks  like the way to execute it in Centos is through the command "7za".

Any idea about what I should do ?
Thank you very much

**Comment by shubhamchandak94** [comment]
Hi,
Can you try replacing the contents of the harc file by the contents in https://gist.github.com/shubhamchandak94/468c9a3b15fd4f82c2a951029218b251
Regards,
Shubham

**Comment by juandaqugo** [comment]
Thank you very much.
